### ISSUE TITLE
Recipe for pressure plates and carpet are the same and cancel out carpet.

### ISSUE THREAD

**Issue by Mildred076** [tristankechlo/TheWoolCollection#3]
Recipe for the wool pressure plates are the same as carpet and it seems to cancel out the carpet recipe completely. Even when using the crafting book and selecting carpet, it makes a pressure plate. I even tried in my 2x2 inventory recipe slot and still makes pressure plate.

**Additional context**  
![2023-08-05_17 15 46](https://github.com/tristankechlo/TheWoolCollection/assets/141526442/d7a96a3a-0258-487e-b512-22458bf208af)

**Comment by tristankechlo** [comment]
Thanks for the report, I noticed that a while ago too.  
But since then I've forgotten about it again.

**Comment by tristankechlo** [comment]
should be fixed with the newest modversion (1.1)

**Comment by Mildred076** [comment]
Thank you!!! Weaving station is a great fix!
